### ISSUE TITLE
Polyfill not working in Oculus Go / Gear VR

### ISSUE THREAD

**Issue by jfcampos** [immersive-web/webxr-polyfill#41]
Currently investigating too, but wanted to share in case any of you has any hints. The polyfill stopped working after (what I think it was) an Oculus Browser update.

User Agent is:
Mozilla/5.0 (Linux; Android 7.1.2; Pacific Build/N2G48H) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/5.0.8.123398067 SamsungBrowser/4.0 Chrome/66.0.3359.203 Mobile VR Safari/537.36

The old WebVR examples work, examples in three.js site work. But none of the webxr-samples work anymore. It gets stuck on the white spinning circle.

requestDevice works, device.supportsSession({immersive:true}) also works. It seems to be related to display.requestAnimationFrame, as I can see this warning after cancelling with the back button in the controller.
[Violation] 'requestAnimationFrame' handler took 2814ms

Seems to be stuck there.

**Comment by jsantell** [comment]
Thanks for reporting, Juan! 

I was able to successfully run the [XR Presentation sample with the polyfill](https://immersive-web.github.io/webxr-samples/xr-presentation.html?allowPolyfill=1) (WebXR disabled, WebVR enabled) -- I don't have a Go/GearVR to test at the moment, but wonder what differences are in those builds to cause this -- the RAF warning seems troublesome.

There's some magic going on due to user gesture requirements and mapping from WebXR->WebVR, resulting in the [first](https://github.com/immersive-web/webxr-polyfill/blob/fad50501d7d3269fbdb4054af408003e6fcbc01d/src/devices/WebVRDevice.js#L193-L199) requestPresent firing on `requestSession` with a dummy canvas, and a [second](https://github.com/immersive-web/webxr-polyfill/blob/fad50501d7d3269fbdb4054af408003e6fcbc01d/src/devices/WebVRDevice.js#L133-L138) requestPresent when `session.baseLayer` is set -- I wonder if this is causing the raf timeout? Can you determine where in [WebVRDevice](https://github.com/immersive-web/webxr-polyfill/blob/fad50501d7d3269fbdb4054af408003e6fcbc01d/src/devices/WebVRDevice.js) the failure is occuring?

**Comment by jfcampos** [comment]
It freezes [here](https://github.com/immersive-web/webxr-polyfill/blob/fad50501d7d3269fbdb4054af408003e6fcbc01d/src/devices/WebVRDevice.js#L363)

I can see it submits 2 frames and gets stuck in the third one.

**Comment by jfcampos** [comment]
More info, the examples work in Firefox Reality.

**Comment by jsantell** [comment]
I made a test case of the double requestPresent used here; would be worth trying it on a GearVR to confirm that it can support that case: https://request-present-double-request.glitch.me/

**Comment by Squareys** [comment]
This does indeed reproduce the issue, I get the spinner as with my app.

**Comment by jsantell** [comment]
Ah that's a bummer. This is an issue because the engagement gesture gate in WebXR doesn't yet have the WebGL context until at a later point when `session.baseLayer` is set. We need to call WebVR's `requestPresent` from the session's `requestSession` due to the engagement gesture gate, but do not yet have a canvas to supply to WebVR.

The spec does allow updating the presentation canvas after the initial call without a user gesture, so the second call to `requestPresent` is when `session.baseLayer` is set. [From the WebVR 1.1 spec](https://immersive-web.github.io/webvr/spec/1.1/#dom-vrdisplay-requestpresent%E2%91%A0):
> If requestPresent() is called outside of an engagement gesture, the promise MUST be rejected unless the VRDisplay was already presenting. This engagement gesture is also sufficient to allow requestPointerLock calls until presentation has ended. The User Agent MAY reject the promise for any other reason. If the VRDisplay is already presenting when requestPresent() is called, the VRDisplay SHOULD update the VRLayerInit list being presented. If a call to requestPresent() is rejected while the VRDisplay is already presenting, the VRDisplay MUST end presentation.

I can't find any GearVR bug trackers to file this, but I'll ping some folks.

In the mean time, we could have a polyfill-specific workaround, but there are a lot of changes coming down the pipe for the WebXR spec that will result in a lot of changes on this end anyway

**Comment by Squareys** [comment]
You can find the forum post [here](https://forums.oculusvr.com/community/discussion/70564/webvr-gear-go-freeze-with-webxr-polyfill/).

**Comment by jfcampos** [comment]
@jsantell Could you describe a bit how would you address that workaround? I'd be interested on doing it on my end so we can have our product working for Oculus Go

**Comment by jsantell** [comment]
I sketched out a possible work around; I have not even executed this code yet, just FYI, but something like this could work: https://github.com/immersive-web/webxr-polyfill/pull/42

I am hesitant about adding new APIs in the polyfill (the scenario where someone uses this API and never actually sets the subsequent baseLayer),  but there are definitely good ways of balancing this to ensure that this workaround is for the polyfill only on certain devices, etc.

May need some fixing of course unless I have time later to look, but let me know if something like this would work, and if it runs (at all!) on the GearVR

**Comment by jfcampos** [comment]
Same behaviour testing #42. In case this helps, here's some log lines when entering VR

> frame
frame
frame

I have a console.log("frame") at the beginning of the function _onXRFrame_ in xr-presentation.html
Then, the third time vrDisplay.submitFrame() is called, it gets stuck.
I press the back button on the controller and then this gets output to the console:

> [.Offscreen-For-WebGL-0xdd2ba600]GL ERROR :GL_INVALID_ENUM : glDiscardFramebufferEXT: attachments was GL_DEPTH_ATTACHMENT
frame
submitFrame has no effect when the VRDisplay is not presenting.

Will continue testing and investigating

**Comment by jsantell** [comment]
@jfcampos can you confirm requestPresent is only being called once, with the correct canvas upfront?

**Comment by jsantell** [comment]
@jfcampos what canvas could it be? is it the same canvas that you're rendering to via three.js or whatever?

**Comment by jfcampos** [comment]
I'm using the xr-presentation.html example to test. 
I added a canvas to the body, and i'm supplying that one as polyfilledPreemptiveBaseLayerCanvas. I can see how it is supplied to requestPresent, but then later the one in onBaseLayerSet is not the same one.

I can't find another place in the code where any canvas is created... except here
https://github.com/immersive-web/webxr-polyfill/blob/008154b56d4813bf1f2c668fc0903120b5ef02b3/src/devices/WebVRDevice.js#L211

but that doesn't get executed.

So i'm puzzled...

**Comment by jsantell** [comment]
Set a debugger breakpoint and check up the stack to see where the canvas comes from maybe? It should be the associated canvas with the context that was used in the `XRWebGLLayer` constructor that gets set via `xrSession.baseLayer = new XRWebGLLayer(...)`

**Comment by jfcampos** [comment]
Ok, some progress. 

You're right, cottontail creates a canvas when _createWebGLContext_ function is called. 

So now, I'm creating the context before requesting the session (still in xr-presentation.html), and passing that canvas as polyfilledPreemptiveBaseLayerCanvas, and now requestPresent is called only once.

I can see frames are processed and submitted continuously, and I can go into and off VR without errors or warnings, but I still see the white spinning circle.

Feels like we're close!

**Comment by Squareys** [comment]
@jsantell @jfcampos Any updates on this? Is there anything I can help with? :)

**Comment by jfcampos** [comment]
I didn't make any progress unfortunately, I'm here ready to test any approach and help where I can. Any help would be appreciated btw! Thanks!

**Comment by Artyom17** [comment]
Hey guys, I am Art from Oculus. Sorry, somehow I completely missed this thread. 
Looking at the issue. Double-requestPresent works, but not in the case when different context (canvas) is specified. This is fixable. However, even if I fix this issue, the https://request-present-double-request.glitch.me/ still won't work since it doesn't call getFrameData. From WebVR spec:
`If getFrameData() was not called prior to calling submitFrame(), the User Agent MAY warn the user of potentially malformed visuals or prevent the frame from being shown at all.`
Can you add getFrameData call please, so I continue my investigation?

**Comment by jsantell** [comment]
@Artyom17 just updated the link at: https://request-present-double-request.glitch.me/

Source code here incase it helps:

```html
<html>
  <head>
    <title>requestPresent test</title>
    <link rel="stylesheet" href="/styles.css">
    <style>
      * { font-size: 130%; color: white; position: relative; }
      body { font-size: 130%; margin: 0; color: white; }
      button { color: black; }
      canvas { z-index: -1; top: 0; left: 0; background-color: green; width: 100vw; height: 100vh; position: absolute; }
      #enter-vr, #high-refresh-rate, label[for="high-refresh-rate"] { display: none; }
      .has-vr #enter-vr, .has-vr #high-refresh-rate, .has-vr label[for="high-refresh-rate"] { display: block; }
      .has-vr #no-vr { display: none; }
    </style>
  </head>
  <body>
    <h1>
      requestPresent double request test
    </h1>
    <button id="enter-vr">
      Enter VR
    </button>
    <input id="high-refresh-rate" name="high-refresh-rate" type="checkbox" /><label for="high-refresh-rate">use highRefreshRate</label>
    <span id="no-vr">no VRDisplay found</span>
    <canvas></canvas>
    <script src="script.js"></script>
  </body>
</html>
```

```js
var vrDisplay;
var body = document.querySelector('body');
var canvas = document.querySelector('canvas');
var highRefreshRate = document.querySelector('#high-refresh-rate');

function init() {
  if (!navigator.getVRDisplays) {
    return;
  }
  
  navigator.getVRDisplays().then(displays => {
    if (displays.length) {
      vrDisplay = displays[0];
      body.classList.add('has-vr');
    }
  });
}
init();

document.querySelector("#enter-vr").addEventListener('click', async function () {
  const extraAttributes = highRefreshRate.checked ? { highRefreshRate: true } : void 0;
  // Test calling `vrDisplay.requestPresent` once with an empty, dummy
  // canvas, and then with the request. This is done in the webxr-polyfill
  // since the canvas is unknown at the time of creating a session, but we need
  // a user gesture for vrDisplay.requestPresent, but only on the first one.
  // https://github.com/immersive-web/webxr-polyfill/blob/fad50501d7d3269fbdb4054af408003e6fcbc01d/src/devices/WebVRDevice.js#L193-L210
  const gl = canvas.getContext('webgl');
  const dummyCanvas = document.createElement('canvas');
  // Context needs to be created for the dummyCanvas (no idea why)
  const dummyCtx = dummyCanvas.getContext('webgl');
  const vrFrameData = new window.VRFrameData();
  
  const right = vrDisplay.getEyeParameters('right');
  const left = vrDisplay.getEyeParameters('left');
  canvas.width = Math.max(left.renderWidth, right.renderWidth) * 2;
  canvas.height = Math.max(left.renderHeight, right.renderHeight);
  
  await vrDisplay.requestPresent([{ source: dummyCanvas }], extraAttributes);
  await vrDisplay.requestPresent([{ source: canvas }], extraAttributes);
  vrDisplay.requestAnimationFrame(onFrame);
  function onFrame() {
    const t = performance.now() / 1000;
    vrDisplay.requestAnimationFrame(onFrame);
    gl.clearColor(Math.sin(t) / 2 + 0.5, Math.cos(t) / 2 + 0.5, 0, 1.0);
    gl.clear(gl.COLOR_BUFFER_BIT);
    vrDisplay.getFrameData(vrFrameData);
    vrDisplay.submitFrame();
  }
  
});
```

**Comment by jfcampos** [comment]
That's awesome @Artyom17 thanks! Is there a date planned for the release?

**Comment by jsantell** [comment]
:raised_hands: :tada: awesome :smile: thanks @Artyom17 @jfcampos for your work in investigating! Is there anything else we can do on the polyfill side? Maybe just a note that Oculus Browser needs to be 5.4+?

**Comment by Artyom17** [comment]
I guess, the note will be fine, yes. Also, just FYI, Oculus Browser 5.4+ will have native WebXR implementation behind the flag (well, to the spec as of about two month ago: it still uses requestDevice / requestSession). BTW, isn't it why you need double requestPresent anyway? Well, XRDevice is removed from the latest spec.

**Comment by jsantell** [comment]
Yeah there hasn't been any changes here yet to accommodate the WebXR API changes from TPAC. I imagine there'll be some state of flux. If using WebXR natively the polyfill shouldn't do anything, so this fix should only be applied if the flag is unchecked, correct?

Reason for double requestPresent isn't due to the requestDevice (doesn't need a user-gesture), but for `requestSession` needing a user gesture that needs to be used for the WebVR `requestPresent` call (or `fullscreen` if polyfilling everything), and not yet having the canvas to present for WebVR (which is set on `session.baseLayer` which can happen anytime after the session has started

**Comment by jfcampos** [comment]
Oculus Browser 5.4 is out and I can confirm the polyfill works, both with and without the native webXR flag! Thanks @Artyom17 @jsantell

**Comment by Squareys** [comment]
I can confirm, [WebVR Pong](https://constructarca.de/game/webvr-pong) works again on Oculus GO also 🎉
Thank you all very much 🙏

**Comment by jsantell** [comment]
@jfcampos @Squareys great to hear! Thanks all!
